apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-app-deployment
  namespace: helloworld
  labels:
    app: helloworld-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld-app
  template:
    metadata:
      labels:
        app: helloworld-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: helloworld-app-deployment
        image: mccowna/helloworld:v1.0.1
        imagePullPolicy: "Always"
        ports:
        - name: http
          containerPort: 80
      nodeSelector:
        kubernetes.io/os: linux
  strategy:
    tyep: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUNavailable: 1
