apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
 # Service name
 name: helloworld-app-deployment
 namespace: helloworld
 labels:
    app: helloworld-app
spec:
 selector:
   # Selector for Pods
   app: helloworld-app
 ports:
   # Port Map
 - port: 8000
   targetPort: 80
   protocol: TCP
 type: LoadBalancer