# A simple example of ClusterConfig object:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Capstone
  region: eu-west-1

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 2
    minSize: 1
    maxSize: 5
    labels:
      nodegroup-type: frontend-workloads
    